name: Run Python Script Daily

on:
  schedule:
    - cron: "0 5 * * *"  # Runs every day at 11 AM UTC (convert to local timezone if needed)

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Run Python script
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }} 
        run: python extract_pdf.py 
