name: Send Email with PDFs

on:
  schedule:
    - cron: "0 5 * * *"  # Runs every day at 5 AM UTC (convert to local timezone if needed)
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: SGSL  # ✅ Force it to use a single SGSL folder

      - name: Change to correct working directory
        run: cd $GITHUB_WORKSPACE && ls -R 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # ✅ Install dependencies

      - name: Run Python script
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}  # ✅ Use GitHub Secret
        run: |
          cd SGSL  # ✅ Go to the correct directory
          python extract_pdf.py  # ✅ Run script

