name: Run Python Script Daily

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 5 AM UTC (11 AM IST)

  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests smtplib email  # Add other dependencies if needed

      - name: Run Python Script
        run: python exctract_pdf.py
